In [31]:
import numpy as np 
import pandas as pd 
import datetime

fl = pd.read_csv('icc/all_player.csv')

In [32]:
fl['Date of birth'] = pd.to_datetime(fl['Date of birth'])
fl

,Name,Date of birth,Team,Batting Style,Bowling Style,ODI Debut,Debut Team,Matches played,Innings,Total Run,Not Out,Highe Score,Batting Avg,Balls faced,Stick rate,100s,50s,4s,6s,Caught,Stumped,Balls,Runs,Wickets,Bowling Avg,Economy,Stick rate.1,5WI,10WM,BBI,BBM
0,Aaron James Redmond,1979-09-23,NEW ZEALAND,Right-hand bat,Leg-break,"October 3,2009",New Zealand v Pakistan,6,6,152,0,52,25.33,259,58.68,0,1,19,0,3,0,--,--,--,--,--,--,--,--,NaN,NaN
1,Adam Fraser Milne,1992-04-13,NEW ZEALAND,Right-hand bat,Right-arm fast,"November 10,2012",Sri Lanka v New Zealand,40,17,168,7,36,16.80,165,101.8,0,0,11,4,21,0,1801,1581,41,38.56,5.267,43.92,0,0,1/8,1/8
2,Adam Craig Parore,1971-01-23,NEW ZEALAND,Right-hand bat,NaN,"October 31,1992",Zimbabwe v New Zealand,179,161,3314,32,108,25.68,4867,68.09,1,14,169,36,116,25,--,--,--,--,--,--,--,--,NaN,NaN
3,Alex Ross Tait,1972-06-13,NEW ZEALAND,Right-hand bat,Right-arm medium,"October 24,1998",New Zealand v Zimbabwe,5,5,35,2,13*,11.66,32,109.3,0,0,2,1,--,--,120,88,3,29.33,4.400,40.00,0,0,2/37,2/37
4,Andre Ryan Adams,1975-07-17,NEW ZEALAND,Right-hand bat,Right-arm fast-medium,"April 10,2001",New Zealand v Sri Lanka,42,34,419,10,45,17.45,417,100.4,0,0,31,18,8,0,1885,1643,53,31.00,5.229,35.56,1,0,5/22,5/22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1962,Victor James Marks,1955-06-25,ENGLAND,Right-hand bat,Off-break,"May 30,1980",England v West Indies,34,24,285,3,44,13.57,434,65.66,0,0,16,0,8,0,1838,1135,44,25.79,3.705,41.77,2,0,5/20,5/20
1963,Vikram Singh Solanki,1976-01-04,ENGLAND,Right-hand bat,Off-break,"January 23,2000",South Africa v England,51,46,1097,5,106,26.75,1502,73.03,2,5,135,7,16,0,111,105,1,105.0,5.675,111.0,0,0,1/17,1/17
1964,Vincent John Wells,1965-06-08,ENGLAND,Right-hand bat,Right-arm medium,"January 10,1999",Australia v England,9,7,141,0,39,20.14,253,55.73,0,0,8,2,7,0,220,189,8,23.62,5.154,27.50,0,0,3/30,3/30
1965,Wayne Larkins,1953-11-22,ENGLAND,Right-hand bat,Right-arm medium,"June 20,1979",England v New Zealand,25,24,591,0,124,24.62,1047,56.44,1,0,66,2,8,0,15,22,0,--,8.800,--,0,0,0/1,0/1
1966,Wilfred Norris Slack,1954-12-12,ENGLAND,Left-hand bat,Right-arm medium,"March 4,1986",West Indies v England,2,2,43,0,34,21.50,85,50.58,0,0,5,1,--,--,--,--,--,--,--,--,--,--,NaN,NaN

In [33]:
fl['Debut Team'] = fl['Debut Team'].str.lower()
deb = fl['Debut Team'].apply(lambda x: x.split(' v'))

In [34]:
fl['Team'] = fl['Team'].str.lower()

def te(x):
    if x[0] == fl['Team'].all():
        return x[1]
    else:
        return x[0]
        
fl['Debut Team'] = deb.apply(te)

In [35]:
pd.set_option('display.max_columns', 31)

In [36]:
fl['Highe Score'] = fl['Highe Score'].str.replace('*','')

In [37]:
def rep(x, a, b):
    return x.replace(a,b)

fl = fl.apply(rep, args=('--','0'))
fl = fl.apply(rep, args=('NaN','0'))

In [38]:
fl.fillna(value=0, inplace=True)
Dat = fl['ODI Debut'].str.replace(',', '-') 
fl['ODI Debut'] = pd.to_datetime(Dat)

In [39]:
cols = fl.columns[7:-2]

fl[cols] = fl[cols].apply(pd.to_numeric)

#fl.to_csv('all_odi_players.csv', index = False)

In [46]:
ODI = pd.read_csv('all_odi_players.csv')
ODI.groupby('Team').count()

,Name,Date of birth,Batting Style,Bowling Style,ODI Debut,Debut Team,Matches played,Innings,Total Run,Not Out,Highe Score,Batting Avg,Balls faced,Stick rate,100s,50s,4s,6s,Caught,Stumped,Balls,Runs,Wickets,Bowling Avg,Economy,Stick rate.1,5WI,10WM,BBI,BBM
Team,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
afghanistan,32,32,32,29,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
australia,192,192,192,164,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192
bangladesh,108,108,108,90,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108
barbados tridents,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
brisbane heat,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
canada,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
cape cobras,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
england,227,227,227,216,227,227,227,227,227,227,227,227,227,227,227,227,227,227,227,227,227,227,227,227,227,227,227,227,227,227
hobart hurricanes,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
hong kong,29,29,29,25,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29
india,205,205,205,187,205,205,205,205,205,205,205,205,205,205,205,205,205,205,205,205,205,205,205,205,205,205,205,205,205,205
ireland,43,43,43,38,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43
lahore lions,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
netherlands,62,62,61,55,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62
new zealand,183,183,183,165,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183,183
pakistan,191,191,191,182,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191
papua new guinea,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
scotland,55,55,55,46,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55
south africa,94,94,94,91,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94
southern express,7,7,7,6,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
sri lanka,153,153,153,137,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153
trinidad and tobago,11,11,11,10,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11
united arab emirates,49,49,49,43,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49
west indies,154,154,153,142,154,154,154,154,154,154,154,154,154,154,154,154,154,154,154,154,154,154,154,154,154,154,154,154,154,154
world xi,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13
zimbabwe,117,117,117,111,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117,117